name:                flock-parenthases-monad
version:             0.1.0.0
github:              "michaeljklein/flock-parenthases-monad"
license:             BSD3
author:              "Michael Klein"
maintainer:          "lambdamichael@gmail.com"
copyright:           "2018 Michael Klein"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/michaeljklein/flock-parenthases-monad#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- text
- containers

library:
  source-dirs: src

executables:
  flock-parenthases-monad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flock-parenthases-monad

tests:
  flock-parenthases-monad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flock-parenthases-monad
